### PR TITLE
Add Authentication and user slice

### PR DESCRIPTION
**Pull request by ahmed025566**
Hello guys, Hope you are doing well.
As you can see I have Implemented the following:

- I have setup linters.
- I have created a landing page which contains Login and Registration component with a button that toggle a state to preview Login or registration.
- I have added a dashboard component which will be our landing page if the user is signed in.
- I have setup redux and Browser Router.
- I have created user slice which handles login and logout and register and checking if the user is logged in or not.
- I have created two routes one for landing page which is loaded if the user is not logged in and dashboard which well be the landing page if the user is logged in and that one will be the page that will preview our items.

### CODE REVIEW

**Review by ahmidou09 — APPROVED** [review]
STATUS APPROVED ✔️ 🎉 🎉 ✔️
Hi @ahmed025566 ,

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Review by alexansaa — APPROVED** [review]
Great Job! Please, keep doing your great work as you have been doing until now!

**Comment by Armynerh** [comment]
APPROVED 
Hi @ahmed025566 ,
Your project is complete! There is nothing else to say other than... it's time to merge it 

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Nice presentation
- Correct Linters

**Review by Armynerh — COMMENTED** [review]
APPROVED 
Hi @ahmed025566 ,
Your project is complete! There is nothing else to say other than... it's time to merge it 

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Well written code
- Correct Linters

**Pull request merged**
